apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podtato
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: podtatoservice
    namespace: demospace
  interval: 1m0s
  path: ./delivery/manifest
  prune: true
  sourceRef:
    kind: GitRepository
    name: podtato
  timeout: 2m0s
  validation: client