apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podtato
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: training
  url: https://github.com/yogeek/podtatohead