apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtatohead
spec:
  selector:
    matchLabels:
      app: podtatohead
  template:
    metadata:
      labels:
        app: podtatohead
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: yogeek/podtatohead:v0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"