apiVersion: v1
kind: Namespace
metadata:
  name: demospace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtatohead
  namespace: demospace  
spec:
  selector:
    matchLabels:
      app: podtatohead
  template:
    metadata:
      labels:
        app: podtatohead
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: yogeek2/podtatohead:v0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
                    
---
apiVersion: v1
kind: Service
metadata:
  name: podtatohead
  namespace: demospace
spec:
  selector:
    app: podtatohead
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer


